#!/usr/bin/env bash
# Modified from the original widevine-installer script to not prompt or
# download files.
# SPDX-License-Identifier: MIT

set -e

# Set to 0 if packaged and the configs are pre-installed
: ${COPY_CONFIGS=1}
: ${DESTDIR:=/}
: ${CONFDIR:=/etc}
: ${LIBDIR:=/usr/lib64}
: ${BINDIR:=/usr/bin}
: ${LIBEXECDIR:=/usr/libexec}
: ${STATEDIR:=/var/lib}
: ${SCRIPT_BASE:=$LIBEXECDIR/widevine-installer}
: ${INSTALL_BASE:=$STATEDIR/widevine}
: ${DISTFILES_BASE:=https://commondatastorage.googleapis.com/chromeos-localmirror/distfiles}
: ${LACROS_NAME:=chromeos-lacros-arm64-squash-zstd}
: ${LACROS_VERSION:=120.0.6098.0}
: ${WIDEVINE_VERSION:=4.10.2662.3}
: ${CHROME_WIDEVINE_BASE:=$LIBDIR/chromium-browser}
: ${MOZ_PREF_BASE:=$LIBDIR/firefox/defaults/pref}

install_configs() {
  cd "$SCRIPT_BASE"
  echo "Copying config files..."
  install -d -m 0755 "$DESTDIR/$INSTALL_BASE"
  install -p -m 0644 -t "$DESTDIR/$INSTALL_BASE" ./conf/README
  install -d -m 0755 "$DESTDIR/$CONFDIR/profile.d/"
  install -p -m 0644 -t "$DESTDIR/$CONFDIR/profile.d/" ./conf/gmpwidevine.sh
  install -d -m 0755 "$DESTDIR/$CHROME_WIDEVINE_BASE"
  ln -sf "$INSTALL_BASE/WidevineCdm" "$DESTDIR/$CHROME_WIDEVINE_BASE/WidevineCdm"
  install -d -m 0755 "$DESTDIR/$MOZ_PREF_BASE"
  install -p -m 0644 -t "$DESTDIR/$MOZ_PREF_BASE" ./conf/gmpwidevine.js
}

echo "Extracting Widevine..."
unsquashfs -q lacros.squashfs 'WidevineCdm/*'

python3 "$SCRIPT_BASE/widevine_fixup.py" squashfs-root/WidevineCdm/_platform_specific/cros_arm64/libwidevinecdm.so libwidevinecdm.so

echo
echo "Installing..."
install -d -m 0755 "$DESTDIR/$INSTALL_BASE"
install -p -m 0755 -t "$DESTDIR/$INSTALL_BASE" libwidevinecdm.so
install -p -m 0644 -t "$DESTDIR/$INSTALL_BASE" squashfs-root/WidevineCdm/manifest.json
install -p -m 0644 -t "$DESTDIR/$INSTALL_BASE" squashfs-root/WidevineCdm/LICENSE

echo "Setting up plugin for Firefox and Chromium-based browsers..."
mkdir -p "$DESTDIR/$INSTALL_BASE"/gmp-widevinecdm/system-installed
ln -sf ../../manifest.json "$DESTDIR/$INSTALL_BASE"/gmp-widevinecdm/system-installed/
ln -sf ../../libwidevinecdm.so "$DESTDIR/$INSTALL_BASE"/gmp-widevinecdm/system-installed/
mkdir -p "$DESTDIR/$INSTALL_BASE"/WidevineCdm/_platform_specific/linux_{arm64,x64}
# Hack because Chromium hardcodes a check for this right now...
touch "$DESTDIR/$INSTALL_BASE"/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
ln -sf ../manifest.json "$DESTDIR/$INSTALL_BASE"/WidevineCdm
ln -sf ../../../libwidevinecdm.so "$DESTDIR/$INSTALL_BASE"/WidevineCdm/_platform_specific/linux_arm64/

if [ "$COPY_CONFIGS" = 1 ]; then
  install_configs
fi
