# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

CRATES="
"

inherit cargo

DESCRIPTION="Rust Token Killer - High-performance CLI proxy to minimize LLM token consumption"
HOMEPAGE="https://www.rtk-ai.app"
SRC_URI="
		https://github.com/rtk-ai/rtk/archive/refs/tags/v${PV}.tar.gz
		https://gentoo.rgst.io/updater_artifacts/${CATEGORY}/${PN}/${PV}/crates.tar.xz -> ${PN}-${PV}-crates.tar.xz
        ${CARGO_CRATE_URIS}
"
RUST_MIN_VER="1.91"

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="amd64 arm64"
