# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
"

inherit cargo

DESCRIPTION="CLI application for interacting with Forgejo"
HOMEPAGE="https://codeberg.org/Cyborus/forgejo-cli"
SRC_URI="
https://codeberg.org/Cyborus/forgejo-cli/archive/v${PV}.tar.gz
https://gentoo.rgst.io/updater_artifacts/${CATEGORY}/${PN}/${PV}/crates.tar.xz -> crates-${PV}.tar.xz
${CARGO_CRATE_URIS}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD-2 BSD ISC MIT MPL-2.0 Unicode-3.0"

BDEPEND="
virtual/pkgconfig
dev-libs/openssl
"

SLOT="0"
KEYWORDS="amd64 arm64"

S="${WORKDIR}/${PN}"

src_configure() {
  export OPENSSL_NO_VENDOR=1

  cargo_src_configure
}
