# Copyright 2025-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8
CRATES=" "

inherit cargo edo shell-completion toolchain-funcs

DESCRIPTION="CLI tool for Forgejo"
HOMEPAGE="https://codeberg.org/Cyborus/forgejo-cli"
SRC_URI="
https://codeberg.org/forgejo-contrib/forgejo-cli/archive/v${PV}.tar.gz
https://gentoo.rgst.io/updater_artifacts/${CATEGORY}/${PN}/${PV}/crates.tar.xz -> crates-${PV}.tar.xz
${CARGO_CRATE_URIS}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD-2 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 Unicode-3.0
	Unicode-DFS-2016
"

RUST_MIN_VER="1.88.0"

BDEPEND="
  virtual/pkgconfig
  dev-libs/openssl
"

SLOT="0"
KEYWORDS="amd64 arm64"

S="${WORKDIR}/${PN}"

src_configure() {
  export OPENSSL_NO_VENDOR=1

  cargo_src_configure
}

src_install() {
  # Support git.rgst.io OOTB
  dodir /etc/fj
  cat >"${D}/etc/fj/client_ids" <<EOF
git.rgst.io ff8a60a0-587e-4110-a06c-b73ca23375e3
EOF

  cargo_src_install

	local target="$(cargo_target_dir)"
	if ! tc-is-cross-compiler; then
		edo "${target}"/fj completion bash > "${T}"/fj.bash
		newbashcomp "${T}"/fj.bash fj
		edo "${target}"/fj completion zsh > "${T}"/fj.zsh
		newzshcomp "${T}"/fj.zsh _fj
		edo "${target}"/fj completion fish > "${T}"/fj.fish
		newfishcomp "${T}"/fj.fish fj.fish
	else
		ewarn "completion not installed because we're cross-compiling"
	fi
}
