name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  # TODO(jaredallard): Remove when act is finally working properly.
  DOCKER_HOST: "tcp://localhost:2375"

# Ensure we run only one job at a time.
concurrency:
  group: "elint-${{ github.repository }}-${{ github.ref }}"

jobs:
  elint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Setup Environment
        working-directory: .tools
        run: |-
          mise run build
          docker pull ghcr.io/jaredallard/overlay:updater
      - name: Run linter
        run: mise run lint
