name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# Ensure we run only one job at a time.
concurrency:
  group: "elint-${{ github.repository }}-${{ github.ref }}"

jobs:
  elint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        with:
          experimental: true
          github_token: ${{ github.token }}
      - name: Get Go directories
        id: go
        run: |
          echo "cache_dir=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "mod_cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.go.outputs.cache_dir }}
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v4
        with:
          path: ${{ steps.go.outputs.mod_cache_dir }}
          key: ${{ runner.os }}-go-mod-cache-${{ hashFiles('**/go.sum') }}
      - name: Setup Environment
        working-directory: .tools
        run: mise run build

      - name: Run linter
        run: mise run lint
