name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# Ensure we run only one job at a time.
concurrency:
  group: "elint-${{ github.repository }}-${{ github.ref }}"

jobs:
  elint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Build tools
        working-directory: .tools
        run: mise run build
      - name: Run linter
        run: mise run lint
